name: open_meteo
description: A simple, fast, asynchronous Dart/Flutter package for accessing the Open-Meteo API.
version: 2.0.3
homepage: https://github.com/neursh/open-meteo-dart
repository: https://github.com/neursh/open-meteo-dart

environment:
  sdk: ^3.0.0

dependencies:
  flat_buffers: '>=23.5.26'
  http: ^1.0.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
